# Generated by Django 5.0 on 2024-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkemail",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Code for confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="profile_image",
            field=models.FileField(
                blank=True, null=True, upload_to="profile", verbose_name="Profile image"
            ),
        ),
    ]
